#!/usr/bin/expect

set timeout 600

spawn /usr/bin/php artisan koel:init

expect "Your name*"
send "$env(ADMIN_NAME)\r"

expect "Your email address*"
send "$env(ADMIN_EMAIL)\r"

expect "Your desired password*"
send "$env(ADMIN_PASSWORD)\r"

expect "Again, just to make sure*"
send "$env(ADMIN_PASSWORD)\r"

expect "Media path*"
send "$env(MEDIA_PATH)\r"

expect "Thanks for using Koel. You rock!"
sleep 1
